[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "camera=(self), microphone=(self), autoplay=(self), fullscreen=(self)"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/js/runtime/*"
  [headers.values]
    Cache-Control = "no-store, max-age=0"
